setup:
  python_version: "3.11"

aws:
  region: "us-east-1"

terraform:
  destroy: true
  auto_approve: true
  backend:
    s3_bucket: "terraform-state-197045787308"
    key: "techchallenge2/terraform.tfstate"
    region: "us-east-1"
    account_id: "197045787308"