name: '1 - [FEAT] Validate and Create PR to Main'

on:
  push:
    branches-ignore:
      - main

jobs:
  pull-request:
    name: Criar PR automático para main
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout da branch que recebeu o push
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar PR automático para main
        if: "!contains(github.event.head_commit.message, '[skip pr]')"
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.ref_name }}
          target_branch: main
          title: 'Auto PR - Merge ${{ github.ref_name }} into main'
          body: |
            Este PR foi criado automaticamente para merge do branch `${{ github.ref_name }}` para `main`.
            
            **Branch de origem:** `${{ github.ref_name }}`
            **Commit:** ${{ github.sha }}
            **Autor:** @${{ github.actor }}
          draft: false
          allow_no_diff: true